version: '3.1'

services:
  mysqldb:
    image: mysql:8.0.32
    container_name: mysql-db
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: dreamDB
      MYSQL_ROOT_PASSWORD: magic

  dream-shopu:
   container_name: dream-shop
   build: .
   restart: always
   ports:
     - 8080:8080
   environment:
    MYSQL_HOST: mysqldb
    MYSQL_PASSWORD: magic
    MYSQL_USER: root

