insert into categories (description, image_name_category, name_category)
values ('Express yourself with our unique collection of pins! Our pins are perfect for adding a touch of personality to your jackets, backpacks, hats, and more. Whether you''re a fan of pop culture, music, animals, or just looking for a fun and quirky accessory, we''ve got you covered. Our pins are made with high-quality materials, ensuring that they will stay in great condition for years to come. With a variety of designs to choose from, you can mix and match to create your own unique style.',
        'https://storage.googleapis.com/dream-shop-380613/8f83d1443145c05d14ca4ae86e23d08c.jpg', 'Pins');
insert into categories (description, image_name_category, name_category)
values ('Keep your keys organized and add a touch of style with our collection of keychains! Our keychains are the perfect way to keep track of your keys while expressing your unique personality. Whether you''re a fan of cute and colorful designs or prefer sleek and sophisticated styles, we''ve got something for everyone. With a variety of shapes, sizes, and materials to choose from, you''re sure to find the perfect keychain to fit your needs.',
        'https://storage.googleapis.com/dream-shop-380613/ded3a22b6b5df99ab6d62a2eb3ed4bbe.jpg', 'Keychains');
insert into categories (description, image_name_category, name_category)
values ('Bring the beauty of famous artworks into your home with our collection of replica paintings. From classic works by the masters to modern favorites, we''ve got a wide selection to choose from. Our replicas are perfect for art lovers who want to enjoy the beauty of famous works without breaking the bank. With a range of sizes and styles available, you can choose the perfect painting to complement your home décor. Shop now and add some artistic flair to your space with our replica paintings!',
        'https://storage.googleapis.com/dream-shop-380613/image094-40.jpg', 'Replica Paintings');
insert into categories (description, image_name_category, name_category)
values ('Add some fun to your collection with our selection of collectible toys! From classic favorites to the latest trends, we''ve got a variety of toys to satisfy every collector. Our collectible toys are made with high-quality materials and attention to detail, making them perfect for display or play. With a range of sizes and styles to choose from, you can build your collection and show off your fandom in style.',
        'https://storage.googleapis.com/dream-shop-380613/513OcGY%2BlgL._AC_SL1000_.jpg', 'Collectible Toys');